// this code is referred from https://github.com/fentec-project/CiFEr
#include<stdio.h>
#include<gmp.h>
#include<stdlib.h>
#include<string.h>
#include "include/cifer/innerprod/simple/ddh.h"
#include "include/cifer/data/vec.h"
#include "include/cifer/data/mat.h"

int Final(const int *a,const int *b,size_t size)
{	//initialization
	size_t l = size; // length of input vectors
	mpz_t bound, fe_key, xy, el;
	mpz_inits(bound, fe_key, xy, el, NULL);
	mpz_set_ui(bound, size); // upper bound for input vector coordinates
	size_t modulus_len = 128; // bit length of prime modulus p
	cfe_ddh s, encryptor, decryptor;
	cfe_ddh_init(&s, l, modulus_len, bound);
	cfe_vec msk, mpk, ciphertext, x, y;
	cfe_ddh_master_keys_init(&msk, &mpk, &s);
//generation of master keys
cfe_ddh_generate_master_keys(&msk, &mpk, &s);

cfe_vec_init(&y,size);
for(size_t i=0;i<size;i++)
{
mpz_set_ui(el,a[i]);
cfe_vec_set(&y,el,i);
}
cfe_ddh_derive_fe_key(fe_key, &s, &msk, &y);
// Simulate instantiation of encryptor 
// Encryptor wants to hide x and should be given
// master public key by the trusted entity
cfe_vec_init(&x,size);
for(size_t i=0;i<size;i++)
{
mpz_set_ui(el,b[i]);
cfe_vec_set(&x,el,i);
}

cfe_ddh_copy(&encryptor, &s);
cfe_ddh_ciphertext_init(&ciphertext, &encryptor);
cfe_ddh_encrypt(&ciphertext, &encryptor, &x, &mpk);

// Simulate instantiation of decryptor that decrypts the cipher 
// generated by encryptor.
cfe_ddh_copy(&decryptor, &s);
cfe_ddh_decrypt(xy, &decryptor, &ciphertext, fe_key, &y);
int xyy;
xyy=mpz_get_si(xy);
//gmp_printf("xy %Zd ",xy);
//printf("xyy %d ",xyy);
return xyy;
}
int main()
{
return 0;
}
